### PR TITLE
Feature/version2

### PR DESCRIPTION
**Pull request by Goesman**
- Added a framework project to contain the new navigation manager.
- Added tests for Descriptor util methods an initialiser

### CODE REVIEW

**Comment by mikeseghers** [comment]
Very clean code, well done! You are still working on test coverage and apple doc right?

**Comment by mikeseghers** [comment]
So we still need to discuss the completion handler stuff, write apple doc and look at code coverage?

**Comment by Goesman** [comment]
@mikeseghers did some changes for you to check.
Open points:
-NSMutableDictionary issue: I still don't know how you would like to see it
-completionblocks solution to cope with nil handlers // GOOD :+1:  or bad :-1:

**Comment by Goesman** [comment]
reopening this as this wasn't supposed to be closed, silly me

**Comment by Goesman** [comment]
See PR #3

**Pull request closed without merging**
